/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubsidyRouteImport } from './routes/subsidy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin.faq'

const SubsidyRoute = SubsidyRouteImport.update({
  id: '/subsidy',
  path: '/subsidy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/subsidy': typeof SubsidyRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/subsidy': typeof SubsidyRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/subsidy': typeof SubsidyRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/comparison'
    | '/contact'
    | '/faqs'
    | '/projects'
    | '/services'
    | '/subsidy'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/comparison'
    | '/contact'
    | '/faqs'
    | '/projects'
    | '/services'
    | '/subsidy'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/leads'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/comparison'
    | '/contact'
    | '/faqs'
    | '/projects'
    | '/services'
    | '/subsidy'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ComparisonRoute: typeof ComparisonRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SubsidyRoute: typeof SubsidyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subsidy': {
      id: '/subsidy'
      path: '/subsidy'
      fullPath: '/subsidy'
      preLoaderRoute: typeof SubsidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ComparisonRoute: ComparisonRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SubsidyRoute: SubsidyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
